// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCpeSHFZ2oRfkIJ_kqdy6TXq0SIUIbRkwE",
  authDomain: "green-f634f.firebaseapp.com",
  projectId: "green-f634f",
  storageBucket: "green-f634f.firebasestorage.app",
  messagingSenderId: "520583233762",
  appId: "1:520583233762:web:383e6c2282c00ba5821ebb",
  measurementId: "G-ZJ7H2HSS6W"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCpeSHFZ2oRfkIJ_kqdy6TXq0SIUIbRkwE",
  authDomain: "green-f634f.firebaseapp.com",
  projectId: "green-f634f",
  storageBucket: "green-f634f.firebasestorage.app",
  messagingSenderId: "520583233762",
  appId: "1:520583233762:web:383e6c2282c00ba5821ebb",
  measurementId: "G-ZJ7H2HSS6W"
  );

  static const FirebaseOptions ios = FirebaseOptions(
   apiKey: "AIzaSyCpeSHFZ2oRfkIJ_kqdy6TXq0SIUIbRkwE",
  authDomain: "green-f634f.firebaseapp.com",
  projectId: "green-f634f",
  storageBucket: "green-f634f.firebasestorage.app",
  messagingSenderId: "520583233762",
  appId: "1:520583233762:web:383e6c2282c00ba5821ebb",
  measurementId: "G-ZJ7H2HSS6W"
  );

  static const FirebaseOptions macos = FirebaseOptions(
     apiKey: "AIzaSyCpeSHFZ2oRfkIJ_kqdy6TXq0SIUIbRkwE",
  authDomain: "green-f634f.firebaseapp.com",
  projectId: "green-f634f",
  storageBucket: "green-f634f.firebasestorage.app",
  messagingSenderId: "520583233762",
  appId: "1:520583233762:web:383e6c2282c00ba5821ebb",
  measurementId: "G-ZJ7H2HSS6W"
  );
}
